---
title: Raspberry Pi Zero Time-Lapse Camera
hero_image: images/banner.png
description: In this resource you will make a wearable time-lapse camera using a Raspberry
  Pi Zero.
original_url: https://raspberrypi.org/learning/raspberry-pi-zero-time-lapse-cam
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-1, programming-2, phys-comp-2, manufacture-1, community-0
interests: photography, big-project, wearable-technology
technologies: electronic-components, python
site_areas: projects
hardware: electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Deciding on your wearable
- title: Attaching the camera
  completion:
  - engaged
- title: Checking your camera
- title: Coding the time-lapse
- title: Attaching a header to the Raspberry Pi Zero
- title: Coding the lights
- title: Starting the time-lapse on boot
- title: Creating the wearable
  completion:
  - internal
- title: What's next?
