---
title: Raspberry Pi Zero Time-Lapse Camera
hero_image: images/banner.png
description: In this resource you will make a wearable time-lapse camera using a Raspberry
  Pi Zero.
original_url: https://raspberrypi.org/learning/raspberry-pi-zero-time-lapse-cam
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: photography, big-project
technologies: physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Raspberry Pi Zero Time-Lapse Camera
- title: Deciding on your wearable
- title: Attaching the camera
- title: Checking your camera
- title: Coding the time-lapse
- title: Attaching a header to the Raspberry Pi Zero
- title: Setting up the software
- title: Coding the lights
- title: Starting the time-lapse on boot
- title: Creating the wearable
- title: What's next?

